/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import application.Cartographer;
import application.ImageBuilder;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileNotFoundException;
import java.util.Arrays;
import javax.swing.ImageIcon;
import losalgoritmos.LosAlgoritmos;

/**
 *
 * @author EliAir
 */
public class GUI extends javax.swing.JFrame {
    private Cartographer c;
    private ImageBuilder ie;
    private MapListModel mapListModel;
    private LosAlgoritmos la;
    private int[] start;
    private int[] goal;
    private char[][] charMatrix;
    private BufferedImage bf;
    
    /**
     * Creates new form GUI
     */
    public GUI() {        
        try { c = new Cartographer(new File("./maps/isound1.map"));
        } catch (FileNotFoundException ex) {}
        ie = new ImageBuilder();
        mapListModel = new MapListModel();
        la = new LosAlgoritmos();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        settingsPanel = new javax.swing.JPanel();
        mapScrollPane = new javax.swing.JScrollPane();
        mapList = new javax.swing.JList();
        startValPanel = new javax.swing.JPanel();
        startValField = new javax.swing.JTextField();
        goalValPanel = new javax.swing.JPanel();
        goalValField = new javax.swing.JTextField();
        routeButton = new javax.swing.JButton();
        mapLabel = new javax.swing.JLabel();

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        settingsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Map Settings"));

        mapList.setModel(mapListModel);
        mapList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        mapList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                mapListValueChanged(evt);
            }
        });
        mapScrollPane.setViewportView(mapList);

        startValPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Goal x,y"));

        startValField.setText("35,35");
        startValField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startValFieldActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout startValPanelLayout = new org.jdesktop.layout.GroupLayout(startValPanel);
        startValPanel.setLayout(startValPanelLayout);
        startValPanelLayout.setHorizontalGroup(
            startValPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(startValPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(startValField)
                .addContainerGap())
        );
        startValPanelLayout.setVerticalGroup(
            startValPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(startValPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(startValField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        goalValPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Start x,y"));

        goalValField.setText("10,10");
        goalValField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goalValFieldActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout goalValPanelLayout = new org.jdesktop.layout.GroupLayout(goalValPanel);
        goalValPanel.setLayout(goalValPanelLayout);
        goalValPanelLayout.setHorizontalGroup(
            goalValPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(goalValPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(goalValField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                .addContainerGap())
        );
        goalValPanelLayout.setVerticalGroup(
            goalValPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(goalValPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(goalValField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        routeButton.setText("Route");
        routeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                routeButtonActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout settingsPanelLayout = new org.jdesktop.layout.GroupLayout(settingsPanel);
        settingsPanel.setLayout(settingsPanelLayout);
        settingsPanelLayout.setHorizontalGroup(
            settingsPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(settingsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(settingsPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(settingsPanelLayout.createSequentialGroup()
                        .add(mapScrollPane, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 139, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(settingsPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(goalValPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(startValPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .add(routeButton))
                .addContainerGap(9, Short.MAX_VALUE))
        );
        settingsPanelLayout.setVerticalGroup(
            settingsPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(settingsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(settingsPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                    .add(mapScrollPane, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 151, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(settingsPanelLayout.createSequentialGroup()
                        .add(goalValPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(startValPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .add(18, 18, 18)
                .add(routeButton)
                .addContainerGap(176, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(mapLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 402, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(settingsPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(mapLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(settingsPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void goalValFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goalValFieldActionPerformed
        drawMap();
        
    }//GEN-LAST:event_goalValFieldActionPerformed

    private void startValFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startValFieldActionPerformed
        drawMap();
    }//GEN-LAST:event_startValFieldActionPerformed

    private void mapListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_mapListValueChanged
        if (!evt.getValueIsAdjusting()) {
            System.out.println(mapList.getSelectedValue());
            drawMap();
        }
    }//GEN-LAST:event_mapListValueChanged

    private void routeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_routeButtonActionPerformed
        route();
    }//GEN-LAST:event_routeButtonActionPerformed

    /**
     * Draws the currently loaded map. Uses the following information:
     * startValField x and y coordinates, goalValField x and y coordinates and 
     * the charMatrix loaded in the system. The map is return as a BufferedImage 
     * by ImageBuilder and drawn to mapLabel jPanel.
     */
    
    public void drawMap(){
        String[] sarr = startValField.getText().split(",");
        this.start = new int[] {Integer.parseInt(sarr[1]),Integer.parseInt(sarr[0])};
        sarr = goalValField.getText().split(",");
        this.goal = new int[] {Integer.parseInt(sarr[1]),Integer.parseInt(sarr[0])};
        
        System.out.println(Arrays.toString(start));
        System.out.println(Arrays.toString(goal));
        
        try {
            c.loadMap((File) mapList.getSelectedValue());
            charMatrix = c.toCharMatrix();
            bf = ie.buildImage(charMatrix, 250, 250, start, goal);
            mapLabel.setIcon(new ImageIcon(bf));
        } catch (Exception ex) {
            System.out.println(ex);
        }        
    }    
    
    /**
     * Runs the routing algorithm and updates the current map with the best route.
     * Uses LosAlgoritmos class for routing and ImageBuilder to update the graphical
     * representation of the map.
     */
    
    public void route(){
        la.loadMap(charMatrix);
        la.loadStart(start[0], start[1]);
        la.loadGoal(goal[0], goal[1]);
        la.astar();
        la.printAllDistances();
        BufferedImage buff=ie.update(la.getBestroute(), 250, 250);
        mapLabel.setIcon(new ImageIcon(buff));
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField goalValField;
    private javax.swing.JPanel goalValPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel mapLabel;
    private javax.swing.JList mapList;
    private javax.swing.JScrollPane mapScrollPane;
    private javax.swing.JButton routeButton;
    private javax.swing.JPanel settingsPanel;
    private javax.swing.JTextField startValField;
    private javax.swing.JPanel startValPanel;
    // End of variables declaration//GEN-END:variables
}
